development:
  adapter: postgresql
  encoding: unicode
  database: involvio_development
  host: localhost
  pool: 5
  username: root
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: involvio_test
  host: localhost
  pool: 5
  username: root
  password: root